// EdgeCommons v0.9.1 +++ Visit edgecommons.org for documentation, updates and examples +++ Copyright (c) 2013 by Simon Widjaja +++ Distributed under the terms of the MIT license (http://www.opensource.org/licenses/mit-license.html) +++ This notice shall be included in all copies or substantial portions of the Software.
// Input 0
(function(a){var d=function(){};d.VERSION="0.0.2";a.Modulog=d})(window);
(function(){var a=function(){};a.VERSION="0.0.2";a.LEVEL_NONE=0;a.LEVEL_ERROR=1;a.LEVEL_WARN=2;a.LEVEL_INFO=3;a.LEVEL_DEBUG=4;a.level=a.LEVEL_DEBUG;var d=null;a.addLogTarget=function(b){"function"===typeof b&&(d=b)};a.debug=function(b,a,c){ModulogLog.level>=ModulogLog.LEVEL_DEBUG&&(b="[ DEBUG "+(a?"| "+a+" ":"")+"] "+b,"undefined"!=typeof console&&"undefined"!=typeof console.debug?c?console.debug(b,c):console.debug(b):"undefined"!=typeof console&&"undefined"!=typeof console.info&&(c?console.info(b,
c):console.info(b)),ModulogLog.__delegate(b,c))};a.info=function(b,a,c){ModulogLog.level>=ModulogLog.LEVEL_INFO&&(b="[ INFO "+(a?"| "+a+" ":"")+"] "+b,"undefined"!=typeof console&&"undefined"!=typeof console.info&&(c?console.info(b,c):console.info(b)),ModulogLog.__delegate(b,c))};a.warn=function(a,e,c){ModulogLog.level>=ModulogLog.LEVEL_WARN&&(a="[ WARN "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.warn&&(c?console.warn(a,c):console.warn(a)),ModulogLog.__delegate(a,
c))};a.error=function(a,e,c){ModulogLog.level>=ModulogLog.LEVEL_ERROR&&(a="[ ERROR "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.error&&(c?console.error(a,c):console.error(a)),ModulogLog.__delegate(a,c))};a.__delegate=function(a,e){d&&(e?d(a+" : "+e.toString()):d(a))};window.Log=window.MLog=window.ModulogLog=a})(window.Modulog);
(function(){var a=function(){};a.VERSION="0.0.1";var d=null,b=ModulogLog;a.get=function(a){for(var b=a.split("."),h=d,g=0;g<b.length;g++){var f=b[g];h.hasOwnProperty(f)||ModulogLog.warn("Config value not found: "+a,"CONFIG");h=h[f]}return h};a.set=function(a,b){for(var h=a.split("."),g=d,f=0;f<h.length-1;f++)g=g[h[f]];g[h.pop()]=b};a.init=function(a,c){"string"===typeof a&&jQuery?$.getJSON(a,function(a){d=a;"function"===typeof c&&c()}):"object"===typeof a?d=a:b.error("Could not init config. init() function expects config object or url to config.js. Latter needs jQuery to be initialized before.",
"Modulog | ModulogConfig")};window.Config=window.MConfig=window.ModulogConfig=a})(window.Modulog);
// Input 1
(function(a){var d=function(){};d.VERSION="0.9.1";a.EC=a.EdgeCommons=d})(window);
// Input 2
(function(a){var d=function(){};d.VERSION="1.0.0";var b=ModulogLog,e=null,c=null;a.loadScript=function(a,g){b.debug("loadScript: "+a,"EdgeCommons | Core");try{yepnope({load:a,callback:function(c){c==a&&(b.debug("Loading external script was successful: "+a,"EdgeCommons | Core"),"function"===typeof g&&g())}})}catch(c){b.error("Loading external script failed: "+a,"EdgeCommons | Core")}};a.getInjectedData=function(a,c){try{c=c||"data";for((!a||!a.getParentSymbol)&&b.error("getInjectedData(): First argument 'sys' is not optional",
"EdgeCommons | Core");a.getParentSymbol();)a=a.getParentSymbol();var d=a.getSymbolElement().find("."+c).html();return $.parseJSON(d)}catch(e){b.error("Reading injected data failed (scriptClassSelector="+c+")","EdgeCommons | Core",e)}};a.setAdaptiveLayouts=function(c,d,f){!c||!c.length?b.error("Error in setAdaptiveLayouts(). Argument 'layouts' is not optional and has to be an array.","EdgeCommons | Core"):(e=c,d&&($(window).resize(function(){a.applyAdaptiveLayout(d,f)}),a.applyAdaptiveLayout(d,f)))};
a.applyAdaptiveLayout=function(a,d){try{a.setVariable("doResizing",function(){var f=a.getComposition().getStage().getSymbolElement().width(),j=a.$(d),i=null;$.each(e,function(a,b){f>=b-20&&(i=b)});c!=i&&(b.debug("Switching to: layout"+i,"EdgeCommons | Core"),c=i,j.html(""),a.createChildSymbol("layout"+i,d));a.$("currentLayout").html(a.getVariable("layout"))}),a.getVariable("doResizing")()}catch(f){console.error(f)}};a.centerStage=function(a){a?a.getComposition().getStage().getSymbolElement().css("margin",
"0px auto"):b.error("Error in centerStage(). Argument 'sym' is not optional.","EdgeCommons | Core")};a.loadComposition=function(c,d){if(!c||!d)b.error("Error in loadComposition(). Arguments 'src' and 'sym' are not optional.","EdgeCommons | Core");else{try{var f=d.getSymbolElement(),e="ec_"+Math.random().toString(36).substring(7);f.html('<iframe id="'+e+'" src="'+c+'" style="overflow: hidden; width: 100%; height: 100%; margin: auto; border: 0 none;"></iframe>');var j=new jQuery.Deferred,i=jQuery("#"+
e),k=i[0].contentWindow;i.load(function(){k.AdobeEdge.bootstrapCallback(function(a){a=k.AdobeEdge.getComposition(a);j.resolve(a,k.AdobeEdge)})})}catch(l){a.error("Error in loadComposition: ","EdgeCommons | Core",l.toString())}return j}};a.Core=d;a.Log=b;a.debug=b.debug;a.info=b.info;a.warn=b.warn;a.error=b.error;a.Config=MConfig})(EdgeCommons);
