// EdgeCommons v1.0.0 +++ Visit edgecommons.org for documentation, updates and examples +++ Copyright (c) 2013 by Simon Widjaja +++ Distributed under the terms of the MIT license (http://www.opensource.org/licenses/mit-license.html) +++ This notice shall be included in all copies or substantial portions of the Software.
// Input 0
(function(a){var d=function(){};d.VERSION="0.0.2";a.Modulog=d})(window);
(function(){var a=function(){};a.VERSION="0.0.2";a.LEVEL_NONE=0;a.LEVEL_ERROR=1;a.LEVEL_WARN=2;a.LEVEL_INFO=3;a.LEVEL_DEBUG=4;a.level=a.LEVEL_DEBUG;var d=null;a.addLogTarget=function(b){"function"===typeof b&&(d=b)};a.debug=function(b,a,c){ModulogLog.level>=ModulogLog.LEVEL_DEBUG&&(b="[ DEBUG "+(a?"| "+a+" ":"")+"] "+b,"undefined"!=typeof console&&"undefined"!=typeof console.debug?c?console.debug(b,c):console.debug(b):"undefined"!=typeof console&&"undefined"!=typeof console.info&&(c?console.info(b,
c):console.info(b)),ModulogLog.__delegate(b,c))};a.info=function(a,e,c){ModulogLog.level>=ModulogLog.LEVEL_INFO&&(a="[ INFO "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.info&&(c?console.info(a,c):console.info(a)),ModulogLog.__delegate(a,c))};a.warn=function(a,e,c){ModulogLog.level>=ModulogLog.LEVEL_WARN&&(a="[ WARN "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.warn&&(c?console.warn(a,c):console.warn(a)),ModulogLog.__delegate(a,
c))};a.error=function(a,e,c){ModulogLog.level>=ModulogLog.LEVEL_ERROR&&(a="[ ERROR "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.error&&(c?console.error(a,c):console.error(a)),ModulogLog.__delegate(a,c))};a.__delegate=function(a,e){d&&(e?d(a+" : "+e.toString()):d(a))};window.Log=window.MLog=window.ModulogLog=a})(window.Modulog);
(function(){var a=function(){};a.VERSION="0.0.1";var d=null,b=ModulogLog;a.get=function(a){for(var c=a.split("."),b=d,h=0;h<c.length;h++){var i=c[h];b.hasOwnProperty(i)||ModulogLog.warn("Config value not found: "+a,"CONFIG");b=b[i]}return b};a.set=function(a,b){for(var f=a.split("."),h=d,i=0;i<f.length-1;i++)h=h[f[i]];h[f.pop()]=b};a.init=function(a,c){"string"===typeof a&&jQuery?$.getJSON(a,function(a){d=a;"function"===typeof c&&c()}):"object"===typeof a?d=a:b.error("Could not init config. init() function expects config object or url to config.js. Latter needs jQuery to be initialized before.",
"Modulog | ModulogConfig")};window.Config=window.MConfig=window.ModulogConfig=a})(window.Modulog);
// Input 1
(function(a){var d=function(){};d.VERSION="1.0.0";a.EC=a.EdgeCommons=d})(window);
// Input 2
(function(a){var d=function(){};d.VERSION="1.0.0";var b=ModulogLog,e=null,c=null,f=null;d.getSymbolName=function(a){var b=a.getVariable("symbolSelector");(a=a.getParentSymbol())&&(b=b.replace(a.getVariable("symbolSelector")+"_",""));return b=b.replace("#","")};a.getInjectedData=function(a,c){try{c=c||"data";for((!a||!a.getParentSymbol)&&b.error("getInjectedData(): First argument 'sys' is not optional","EdgeCommons | Core");a.getParentSymbol();)a=a.getParentSymbol();var d=a.getSymbolElement().find("."+
c).html();return $.parseJSON(d)}catch(e){b.error("Reading injected data failed (scriptClassSelector="+c+")","EdgeCommons | Core",e)}};a.setAdaptiveLayouts=function(c,d,l,m){!c||!c.length?b.error("Error in setAdaptiveLayouts(). Argument 'layouts' is not optional and has to be an array.","EdgeCommons | Core"):(e=c,d&&("function"==typeof m&&(f=m),$(window).resize(function(){a.applyAdaptiveLayout(d,l)}),a.applyAdaptiveLayout(d,l)))};a.applyAdaptiveLayout=function(a,b){try{a.setVariable("doResizing",function(){var d=
a.getComposition().getStage().getSymbolElement().width(),j=a.$(b),g=null;$.each(e,function(a,b){d>=b-20&&(g=b)});c!=g&&(c=g,j.html(""),j=a.createChildSymbol("layout"+g,b),"function"==typeof f&&f(g,j));a.$("currentLayout").html(a.getVariable("layout"))}),a.getVariable("doResizing")()}catch(d){console.error(d)}};a.centerStage=function(a){a?a.getComposition().getStage().getSymbolElement().css("margin","0px auto"):b.error("Error in centerStage(). Argument 'sym' is not optional.","EdgeCommons | Core")};
a.loadComposition=function(c,d){if(!c||!d)b.error("Error in loadComposition(). Arguments 'src' and 'sym' are not optional.","EdgeCommons | Core");else{try{var e=d.getSymbolElement(),f="ec_"+Math.random().toString(36).substring(7);e.html('<iframe id="'+f+'" src="'+c+'" style="overflow: hidden; width: 100%; height: 100%; margin: auto; border: 0 none; background-color: rgba(255,255,255,0)"></iframe>');var j=new jQuery.Deferred,g=jQuery("#"+f),k=g[0].contentWindow;g.load(function(){k.AdobeEdge.bootstrapCallback(function(a){a=
k.AdobeEdge.getComposition(a);j.resolve(a,k.AdobeEdge)})})}catch(n){a.error("Error in loadComposition: ","EdgeCommons | Core",n.toString())}return j}};a.Core=d;a.Log=b;a.debug=b.debug;a.info=b.info;a.warn=b.warn;a.error=b.error;a.Config=MConfig})(EdgeCommons);
